name:                library1
version:             0.0.0.1
license:             BSD3
author:              "Leonidas Loucas"
maintainer:          "merc1031@gmail.com"
copyright:           "2022 Leonidas Loucas"

description:         Please see the README

dependencies:
- base                  >= 4        && < 5

library:
  source-dirs: src
  ghc-options:
    - -O2
    - -Wall

tests:
  library1-test:
    main:                TestDriver.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - library1
    - hspec
    - hspec-discover
    - HUnit
    - tasty
    - tasty-discover
    - tasty-hspec
    - tasty-quickcheck
    - QuickCheck

executables:
  exe:
    main:                Scratch.hs
    source-dirs:         exe
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - library1
    - hspec
    - hspec-discover
    - HUnit
    - tasty
    - tasty-discover
    - tasty-hspec
    - tasty-quickcheck
    - QuickCheck
